depth:
  start: 2
  end: 3
base_dim:
  - 128 
  - 256
  - 512
latent_dim:
  - 32
  - 64
activation_en:
  - "relu"
  - "leaky_relu"
  - "tanh"
  - "sigmoid"
activation_de:
  - "relu"
  - "leaky_relu"
  - "tanh"
  - "sigmoid"
dropout:
  start: 0.0
  end: 0.3
optimizer:
  - "adam"
lr_scheduler:
  - "plateau"
lr:
  start: 1e-6
  end: 3e-2
weight_decay:
  start: 1e-6
  end: 1e-1
adam_beta1:
  start: 0.9
  end: 0.9
adam_beta2:
  start: 0.999
  end: 0.999
sgd_momentum:
  start: 0.0
  end: 0.0
gradient_clip:
  - 0.5
  - 1.0
  - 2.0
batch_size:
  - 64
  - 128
  - 256
  - 512
patience:
  start: 5
  end: 9
noise_gauss_std:
  start: 0.1
  end: 0.3
noise_mask_prob:
  start: 0.05
  end: 0.1
cont_weight:
  start: 0.0
  end: 2.0
cat_weight:
  start: 0.0
  end: 2.0