regions = {
    'AD': 'Andorra',
    'AE': 'United Arab Emirates',
    'AF': 'Afghanistan',
    'AG': 'Antigua and Barbuda',
    'AI': 'Anguilla',
    'AL': 'Albania',
    'AM': 'Armenia',
    'AO': 'Angola',
    'AQ': 'Antarctica',
    'AR': 'Argentina',
    'AS': 'American Samoa',
    'AT': 'Austria',
    'AU': 'Australia',
    'AW': 'Aruba',
    'AX': 'Åland Islands',
    'AZ': 'Azerbaijan',
    'BA': 'Bosnia and Herzegovina',
    'BB': 'Barbados',
    'BD': 'Bangladesh',
    'BE': 'Belgium',
    'BF': 'Burkina Faso',
    'BG': 'Bulgaria',
    'BH': 'Bahrain',
    'BI': 'Burundi',
    'BJ': 'Benin',
    'BL': 'Saint Barthélemy',
    'BM': 'Bermuda',
    'BN': 'Brunei Darussalam',
    'BO': 'Bolivia (Plurinational State of)',
    'BQ': 'Bonaire, Sint Eustatius and Saba',
    'BR': 'Brazil',
    'BS': 'Bahamas',
    'BT': 'Bhutan',
    'BV': 'Bouvet Island',
    'BW': 'Botswana',
    'BY': 'Belarus',
    'BZ': 'Belize',
    'CA': 'Canada',
    'CC': 'Cocos (Keeling) Islands',
    'CD': 'Congo (Democratic Republic of the)',
    'CF': 'Central African Republic',
    'CG': 'Congo',
    'CH': 'Switzerland',
    'CI': "Côte d'Ivoire",
    'CK': 'Cook Islands',
    'CL': 'Chile',
    'CM': 'Cameroon',
    'CN': 'China',
    'CO': 'Colombia',
    'CR': 'Costa Rica',
    'CU': 'Cuba',
    'CV': 'Cabo Verde',
    'CW': 'Curaçao',
    'CX': 'Christmas Island',
    'CY': 'Cyprus',
    'CZ': 'Czechia',
    'DE': 'Germany',
    'DJ': 'Djibouti',
    'DK': 'Denmark',
    'DM': 'Dominica',
    'DO': 'Dominican Republic',
    'DZ': 'Algeria',
    'EC': 'Ecuador',
    'EE': 'Estonia',
    'EG': 'Egypt',
    'EH': 'Western Sahara',
    'ER': 'Eritrea',
    'ES': 'Spain',
    'ET': 'Ethiopia',
    'FI': 'Finland',
    'FJ': 'Fiji',
    'FK': 'Falkland Islands (Malvinas)',
    'FM': 'Micronesia (Federated States of)',
    'FO': 'Faroe Islands',
    'FR': 'France',
    'GA': 'Gabon',
    'GB': 'United Kingdom',
    'GD': 'Grenada',
    'GE': 'Georgia',
    'GF': 'French Guiana',
    'GG': 'Guernsey',
    'GH': 'Ghana',
    'GI': 'Gibraltar',
    'GL': 'Greenland',
    'GM': 'Gambia',
    'GN': 'Guinea',
    'GP': 'Guadeloupe',
    'GQ': 'Equatorial Guinea',
    'GR': 'Greece',
    'GS': 'South Georgia and the South Sandwich Islands',
    'GT': 'Guatemala',
    'GU': 'Guam',
    'GW': 'Guinea-Bissau',
    'GY': 'Guyana',
    'HK': 'Hong Kong',
    'HM': 'Heard Island and McDonald Islands',
    'HN': 'Honduras',
    'HR': 'Croatia',
    'HT': 'Haiti',
    'HU': 'Hungary',
    'ID': 'Indonesia',
    'IE': 'Ireland',
    'IL': 'Israel',
    'IM': 'Isle of Man',
    'IN': 'India',
    'IO': 'British Indian Ocean Territory',
    'IQ': 'Iraq',
    'IR': 'Iran (Islamic Republic of)',
    'IS': 'Iceland',
    'IT': 'Italy',
    'JE': 'Jersey',
    'JM': 'Jamaica',
    'JO': 'Jordan',
    'JP': 'Japan',
    'KE': 'Kenya',
    'KG': 'Kyrgyzstan',
    'KH': 'Cambodia',
    'KI': 'Kiribati',
    'KM': 'Comoros',
    'KN': 'Saint Kitts and Nevis',
    'KP': "Korea (Democratic People's Republic of)",
    'KR': 'Korea (Republic of)',
    'KW': 'Kuwait',
    'KY': 'Cayman Islands',
    'KZ': 'Kazakhstan',
    'LA': "Lao People's Democratic Republic",
    'LB': 'Lebanon',
    'LC': 'Saint Lucia',
    'LI': 'Liechtenstein',
    'LK': 'Sri Lanka',
    'LR': 'Liberia',
    'LS': 'Lesotho',
    'LT': 'Lithuania',
    'LU': 'Luxembourg',
    'LV': 'Latvia',
    'LY': 'Libya',
    'MA': 'Morocco',
    'MC': 'Monaco',
    'MD': 'Moldova (Republic of)',
    'ME': 'Montenegro',
    'MF': 'Saint Martin (French part)',
    'MG': 'Madagascar',
    'MH': 'Marshall Islands',
    'MK': 'North Macedonia',
    'ML': 'Mali',
    'MM': 'Myanmar',
    'MN': 'Mongolia',
    'MO': 'Macao',
    'MP': 'Northern Mariana Islands',
    'MQ': 'Martinique',
    'MR': 'Mauritania',
    'MS': 'Montserrat',
    'MT': 'Malta',
    'MU': 'Mauritius',
    'MV': 'Maldives',
    'MW': 'Malawi',
    'MX': 'Mexico',
    'MY': 'Malaysia',
    'MZ': 'Mozambique',
    'NA': 'Namibia',
    'NC': 'New Caledonia',
    'NE': 'Niger',
    'NF': 'Norfolk Island',
    'NG': 'Nigeria',
    'NI': 'Nicaragua',
    'NL': 'Netherlands',
    'NO': 'Norway',
    'NP': 'Nepal',
    'NR': 'Nauru',
    'NU': 'Niue',
    'NZ': 'New Zealand',
    'OM': 'Oman',
    'PA': 'Panama',
    'PE': 'Peru',
    'PF': 'French Polynesia',
    'PG': 'Papua New Guinea',
    'PH': 'Philippines',
    'PK': 'Pakistan',
    'PL': 'Poland',
    'PM': 'Saint Pierre and Miquelon',
    'PN': 'Pitcairn',
    'PR': 'Puerto Rico',
    'PS': 'Palestine, State of',
    'PT': 'Portugal',
    'PW': 'Palau',
    'PY': 'Paraguay',
    'QA': 'Qatar',
    'RE': 'Réunion',
    'RO': 'Romania',
    'RS': 'Serbia',
    'RU': 'Russian Federation',
    'RW': 'Rwanda',
    'SA': 'Saudi Arabia',
    'SB': 'Solomon Islands',
    'SC': 'Seychelles',
    'SD': 'Sudan',
    'SE': 'Sweden',
    'SG': 'Singapore',
    'SH': 'Saint Helena, Ascension and Tristan da Cunha',
    'SI': 'Slovenia',
    'SJ': 'Svalbard and Jan Mayen',
    'SK': 'Slovakia',
    'SL': 'Sierra Leone',
    'SM': 'San Marino',
    'SN': 'Senegal',
    'SO': 'Somalia',
    'SR': 'Suriname',
    'SS': 'South Sudan',
    'ST': 'Sao Tome and Principe',
    'SV': 'El Salvador',
    'SX': 'Sint Maarten (Dutch part)',
    'SY': 'Syrian Arab Republic',
    'SZ': 'Eswatini',
    'TC': 'Turks and Caicos Islands',
    'TD': 'Chad',
    'TF': 'French Southern Territories',
    'TG': 'Togo',
    'TH': 'Thailand',
    'TJ': 'Tajikistan',
    'TK': 'Tokelau',
    'TL': 'Timor-Leste',
    'TM': 'Turkmenistan',
    'TN': 'Tunisia',
    'TO': 'Tonga',
    'TR': 'Türkiye',
    'TT': 'Trinidad and Tobago',
    'TV': 'Tuvalu',
    'TW': 'Taiwan, Province of China',
    'TZ': 'Tanzania, United Republic of',
    'UA': 'Ukraine',
    'UG': 'Uganda',
    'UM': 'United States Minor Outlying Islands',
    'US': 'United States of America',
    'UY': 'Uruguay',
    'UZ': 'Uzbekistan',
    'VA': 'Holy See',
    'VC': 'Saint Vincent and the Grenadines',
    'VE': 'Venezuela (Bolivarian Republic of)',
    'VG': 'Virgin Islands (British)',
    'VI': 'Virgin Islands (U.S.)',
    'VN': 'Viet Nam',
    'VU': 'Vanuatu',
    'WF': 'Wallis and Futuna',
    'WS': 'Samoa',
    'XK': 'Kosovo',
    'YE': 'Yemen',
    'YT': 'Mayotte',
    'ZA': 'South Africa',
    'ZM': 'Zambia',
    'ZW': 'Zimbabwe'
 }

continental_regions = {
    "africa": [
        "DZ", "AO", "BJ", "BW", "BF", "BI", "CM", "CV", "CF", "TD", "KM", "CG", "CD", "CI", "DJ", "EG", "GQ", "ER", "SZ", "ET", "GA", "GM", "GH", "GN", "GW", "KE", "LS", "LR", "LY", "MG", "MW", "ML", "MR", "MU", "YT", "MA", "MZ", "NA", "NE", "NG", "RE", "RW", "SH", "ST", "SN", "SC", "SL", "SO", "ZA", "SS", "SD", "TZ", "TG", "TN", "UG", "EH", "ZM", "ZW"
    ],

    "antarctica": [
        "AQ", "BV",  "GS", "HM", "TF"
    ],

    "asia": [
        "AF", "AM", "AZ", "BH", "BD", "BT", "BN", "KH", "CN", "CX", "CC", "CY", "GE", "HK", "IN", "ID", "IO", "IR", "IQ", "IL", "JP", "JO", "KZ", "KP", "KR", "KW", "KG", "LA", "LB", "MO", "MY", "MV", "MN", "MM", "NP", "OM", "PK", "PS", "PH", "QA", "SA", "SG", "LK", "SY", "TW", "TJ", "TH", "TL", "TR", "TM", "AE", "UZ", "VN", "YE"
    ],

    "europe": [
        "AL", "AD", "AT", "BY", "BE", "BA", "BG", "CH", "HR", "CZ", "DK", "EE", "FI", "FR", "DE", "GI", "GR", "HU", "IS", "IE", "IT", "XK", "LV", "LI", "LT", "LU", "MT", "MD", "MC", "ME", "NL", "MK", "NO", "PL", "PT", "RO", "RU", "SM", "RS", "SK", "SI", "ES", "SE", "UA", "GB", "VA", "JE", "GG", "IM", "SJ", "AX"
    ],

    "oceania": [
        "AS", "AU", "CK", "FJ", "PF", "GU", "KI", "MH", "FM", "NR", "NC", "NZ", "NU", "NF", "MP", "PW", "PG", "PN", "WS", "SB", "TK", "TO", "TV", "VU", "WF"
    ],

    "north america": [
        "AI", "AG", "AW", "BS", "BB", "BZ", "BM", "CA", "CR", "CU", "CW", "DM", "DO", "SV", "GL", "GD", "GP", "GT", "HT", "HN", "JM", "MQ", "MX", "MS", "NI", "PA", "PR", "BL", "KN", "LC", "MF", "PM", "VC", "SX", "TT", "TC", "VG", "VI", "UM", "US"
    ],

    "south america": [
        "AR", "BO", "BR", "CL", "CO", "EC", "FK", "GF", "GY", "PY", "PE", "SR", "UY", "VE"
    ]
}

timezones = {
    "AD": {"zone": "Europe/Andorra", "offset": "UTC+1"},
    "AE": {"zone": "Asia/Dubai", "offset": "UTC+4"},
    "AF": {"zone": "Asia/Kabul", "offset": "UTC+4:30"},
    "AG": {"zone": "America/Antigua", "offset": "UTC−4"},
    "AI": {"zone": "America/Anguilla", "offset": "UTC−4"},
    "AL": {"zone": "Europe/Tirane", "offset": "UTC+1"},
    "AM": {"zone": "Asia/Yerevan", "offset": "UTC+4"},
    "AO": {"zone": "Africa/Luanda", "offset": "UTC+1"},
    "AQ": {"zone": "Antarctica/Casey", "offset": "UTC+8"},
    "AR": {"zone": "America/Argentina/Buenos_Aires", "offset": "UTC−3"},
    "AS": {"zone": "Pacific/Pago_Pago", "offset": "UTC−11"},
    "AT": {"zone": "Europe/Vienna", "offset": "UTC+1"},
    "AU": {"zone": "Australia/Sydney", "offset": "UTC+10"},
    "AW": {"zone": "America/Aruba", "offset": "UTC−4"},
    "AX": {"zone": "Europe/Mariehamn", "offset": "UTC+2"},
    "AZ": {"zone": "Asia/Baku", "offset": "UTC+4"},
    "BA": {"zone": "Europe/Sarajevo", "offset": "UTC+1"},
    "BB": {"zone": "America/Barbados", "offset": "UTC−4"},
    "BD": {"zone": "Asia/Dhaka", "offset": "UTC+6"},
    "BE": {"zone": "Europe/Brussels", "offset": "UTC+1"},
    "BF": {"zone": "Africa/Ouagadougou", "offset": "UTC"},
    "BG": {"zone": "Europe/Sofia", "offset": "UTC+2"},
    "BH": {"zone": "Asia/Bahrain", "offset": "UTC+3"},
    "BI": {"zone": "Africa/Bujumbura", "offset": "UTC+2"},
    "BJ": {"zone": "Africa/Porto-Novo", "offset": "UTC+1"},
    "BL": {"zone": "America/St_Barthelemy", "offset": "UTC−4"},
    "BM": {"zone": "Atlantic/Bermuda", "offset": "UTC−4"},
    "BN": {"zone": "Asia/Brunei", "offset": "UTC+8"},
    "BO": {"zone": "America/La_Paz", "offset": "UTC−4"},
    "BQ": {"zone": "America/Kralendijk", "offset": "UTC−4"},
    "BR": {"zone": "America/Sao_Paulo", "offset": "UTC−3"},
    "BS": {"zone": "America/Nassau", "offset": "UTC−5"},
    "BT": {"zone": "Asia/Thimphu", "offset": "UTC+6"},
    "BV": {"zone": "Europe/Oslo", "offset": "UTC+1"},
    "BW": {"zone": "Africa/Gaborone", "offset": "UTC+2"},
    "BY": {"zone": "Europe/Minsk", "offset": "UTC+3"},
    "BZ": {"zone": "America/Belize", "offset": "UTC−6"},
    "CA": {"zone": "America/Toronto", "offset": "UTC−5"},
    "CC": {"zone": "Indian/Cocos", "offset": "UTC+6:30"},
    "CD": {"zone": "Africa/Kinshasa", "offset": "UTC+1"},
    "CF": {"zone": "Africa/Bangui", "offset": "UTC+1"},
    "CG": {"zone": "Africa/Brazzaville", "offset": "UTC+1"},
    "CH": {"zone": "Europe/Zurich", "offset": "UTC+1"},
    "CI": {"zone": "Africa/Abidjan", "offset": "UTC"},
    "CK": {"zone": "Pacific/Rarotonga", "offset": "UTC−10"},
    "CL": {"zone": "America/Santiago", "offset": "UTC−4"},
    "CM": {"zone": "Africa/Douala", "offset": "UTC+1"},
    "CN": {"zone": "Asia/Shanghai", "offset": "UTC+8"},
    "CO": {"zone": "America/Bogota", "offset": "UTC−5"},
    "CR": {"zone": "America/Costa_Rica", "offset": "UTC−6"},
    "CU": {"zone": "America/Havana", "offset": "UTC−5"},
    "CV": {"zone": "Atlantic/Cape_Verde", "offset": "UTC−1"},
    "CW": {"zone": "America/Curacao", "offset": "UTC−4"},
    "CX": {"zone": "Indian/Christmas", "offset": "UTC+7"},
    "CY": {"zone": "Asia/Nicosia", "offset": "UTC+2"},
    "CZ": {"zone": "Europe/Prague", "offset": "UTC+1"},
    "DE": {"zone": "Europe/Berlin", "offset": "UTC+1"},
    "DJ": {"zone": "Africa/Djibouti", "offset": "UTC+3"},
    "DK": {"zone": "Europe/Copenhagen", "offset": "UTC+1"},
    "DM": {"zone": "America/Dominica", "offset": "UTC−4"},
    "DO": {"zone": "America/Santo_Domingo", "offset": "UTC−4"},
    "DZ": {"zone": "Africa/Algiers", "offset": "UTC+1"},
    "EC": {"zone": "America/Guayaquil", "offset": "UTC−5"},
    "EE": {"zone": "Europe/Tallinn", "offset": "UTC+2"},
    "EG": {"zone": "Africa/Cairo", "offset": "UTC+2"},
    "EH": {"zone": "Africa/El_Aaiun", "offset": "UTC+1"},
    "ER": {"zone": "Africa/Asmara", "offset": "UTC+3"},
    "ES": {"zone": "Europe/Madrid", "offset": "UTC+1"},
    "ET": {"zone": "Africa/Addis_Ababa", "offset": "UTC+3"},
    "FI": {"zone": "Europe/Helsinki", "offset": "UTC+2"},
    "FJ": {"zone": "Pacific/Fiji", "offset": "UTC+12"},
    "FK": {"zone": "Atlantic/Stanley", "offset": "UTC−3"},
    "FM": {"zone": "Pacific/Pohnpei", "offset": "UTC+11"},
    "FO": {"zone": "Atlantic/Faroe", "offset": "UTC"},
    "FR": {"zone": "Europe/Paris", "offset": "UTC+1"},
    "GA": {"zone": "Africa/Libreville", "offset": "UTC+1"},
    "GB": {"zone": "Europe/London", "offset": "UTC"},
    "GD": {"zone": "America/Grenada", "offset": "UTC−4"},
    "GE": {"zone": "Asia/Tbilisi", "offset": "UTC+4"},
    "GF": {"zone": "America/Cayenne", "offset": "UTC−3"},
    "GG": {"zone": "Europe/Guernsey", "offset": "UTC"},
    "GH": {"zone": "Africa/Accra", "offset": "UTC"},
    "GI": {"zone": "Europe/Gibraltar", "offset": "UTC+1"},
    "GL": {"zone": "America/Nuuk", "offset": "UTC−3"},
    "GM": {"zone": "Africa/Banjul", "offset": "UTC"},
    "GN": {"zone": "Africa/Conakry", "offset": "UTC"},
    "GP": {"zone": "America/Guadeloupe", "offset": "UTC−4"},
    "GQ": {"zone": "Africa/Malabo", "offset": "UTC+1"},
    "GR": {"zone": "Europe/Athens", "offset": "UTC+2"},
    "GS": {"zone": "Atlantic/South_Georgia", "offset": "UTC−2"},
    "GT": {"zone": "America/Guatemala", "offset": "UTC−6"},
    "GU": {"zone": "Pacific/Guam", "offset": "UTC+10"},
    "GW": {"zone": "Africa/Bissau", "offset": "UTC"},
    "GY": {"zone": "America/Guyana", "offset": "UTC−4"},
    "HK": {"zone": "Asia/Hong_Kong", "offset": "UTC+8"},
    "HM": {"zone": "Indian/Kerguelen", "offset": "UTC+5"},
    "HN": {"zone": "America/Tegucigalpa", "offset": "UTC−6"},
    "HR": {"zone": "Europe/Zagreb", "offset": "UTC+1"},
    "HT": {"zone": "America/Port-au-Prince", "offset": "UTC−5"},
    "HU": {"zone": "Europe/Budapest", "offset": "UTC+1"},
    "ID": {"zone": "Asia/Jakarta", "offset": "UTC+7"},
    "IE": {"zone": "Europe/Dublin", "offset": "UTC"},
    "IL": {"zone": "Asia/Jerusalem", "offset": "UTC+2"},
    "IM": {"zone": "Europe/Isle_of_Man", "offset": "UTC"},
    "IN": {"zone": "Asia/Kolkata", "offset": "UTC+5:30"},
    "IO": {"zone": "Indian/Chagos", "offset": "UTC+6"},
    "IQ": {"zone": "Asia/Baghdad", "offset": "UTC+3"},
    "IR": {"zone": "Asia/Tehran", "offset": "UTC+3:30"},
    "IS": {"zone": "Atlantic/Reykjavik", "offset": "UTC"},
    "IT": {"zone": "Europe/Rome", "offset": "UTC+1"},
    "JE": {"zone": "Europe/Jersey", "offset": "UTC"},
    "JM": {"zone": "America/Jamaica", "offset": "UTC−5"},
    "JO": {"zone": "Asia/Amman", "offset": "UTC+2"},
    "JP": {"zone": "Asia/Tokyo", "offset": "UTC+9"},
    "KE": {"zone": "Africa/Nairobi", "offset": "UTC+3"},
    "KG": {"zone": "Asia/Bishkek", "offset": "UTC+6"},
    "KH": {"zone": "Asia/Phnom_Penh", "offset": "UTC+7"},
    "KI": {"zone": "Pacific/Tarawa", "offset": "UTC+12"},
    "KM": {"zone": "Indian/Comoro", "offset": "UTC+3"},
    "KN": {"zone": "America/St_Kitts", "offset": "UTC−4"},
    "KP": {"zone": "Asia/Pyongyang", "offset": "UTC+9"},
    "KR": {"zone": "Asia/Seoul", "offset": "UTC+9"},
    "KW": {"zone": "Asia/Kuwait", "offset": "UTC+3"},
    "KY": {"zone": "America/Cayman", "offset": "UTC−5"},
    "KZ": {"zone": "Asia/Almaty", "offset": "UTC+6"},
    "LA": {"zone": "Asia/Vientiane", "offset": "UTC+7"},
    "LB": {"zone": "Asia/Beirut", "offset": "UTC+2"},
    "LC": {"zone": "America/St_Lucia", "offset": "UTC−4"},
    "LI": {"zone": "Europe/Vaduz", "offset": "UTC+1"},
    "LK": {"zone": "Asia/Colombo", "offset": "UTC+5:30"},
    "LR": {"zone": "Africa/Monrovia", "offset": "UTC"},
    "LS": {"zone": "Africa/Maseru", "offset": "UTC+2"},
    "LT": {"zone": "Europe/Vilnius", "offset": "UTC+2"},
    "LU": {"zone": "Europe/Luxembourg", "offset": "UTC+1"},
    "LV": {"zone": "Europe/Riga", "offset": "UTC+2"},
    "LY": {"zone": "Africa/Tripoli", "offset": "UTC+2"},
    "MA": {"zone": "Africa/Casablanca", "offset": "UTC"},
    "MC": {"zone": "Europe/Monaco", "offset": "UTC+1"},
    "MD": {"zone": "Europe/Chisinau", "offset": "UTC+2"},
    "ME": {"zone": "Europe/Podgorica", "offset": "UTC+1"},
    "MF": {"zone": "America/Marigot", "offset": "UTC−4"},
    "MG": {"zone": "Indian/Antananarivo", "offset": "UTC+3"},
    "MH": {"zone": "Pacific/Majuro", "offset": "UTC+12"},
    "MK": {"zone": "Europe/Skopje", "offset": "UTC+1"},
    "ML": {"zone": "Africa/Bamako", "offset": "UTC"},
    "MM": {"zone": "Asia/Yangon", "offset": "UTC+6:30"},
    "MN": {"zone": "Asia/Ulaanbaatar", "offset": "UTC+8"},
    "MO": {"zone": "Asia/Macau", "offset": "UTC+8"},
    "MP": {"zone": "Pacific/Saipan", "offset": "UTC+10"},
    "MQ": {"zone": "America/Martinique", "offset": "UTC−4"},
    "MR": {"zone": "Africa/Nouakchott", "offset": "UTC"},
    "MS": {"zone": "America/Montserrat", "offset": "UTC−4"},
    "MT": {"zone": "Europe/Malta", "offset": "UTC+1"},
    "MU": {"zone": "Indian/Mauritius", "offset": "UTC+4"},
    "MV": {"zone": "Indian/Maldives", "offset": "UTC+5"},
    "MW": {"zone": "Africa/Blantyre", "offset": "UTC+2"},
    "MX": {"zone": "America/Mexico_City", "offset": "UTC−6"},
    "MY": {"zone": "Asia/Kuala_Lumpur", "offset": "UTC+8"},
    "MZ": {"zone": "Africa/Maputo", "offset": "UTC+2"},
    "NA": {"zone": "Africa/Windhoek", "offset": "UTC+2"},
    "NC": {"zone": "Pacific/Noumea", "offset": "UTC+11"},
    "NE": {"zone": "Africa/Niamey", "offset": "UTC+1"},
    "NF": {"zone": "Pacific/Norfolk", "offset": "UTC+11"},
    "NG": {"zone": "Africa/Lagos", "offset": "UTC+1"},
    "NI": {"zone": "America/Managua", "offset": "UTC−6"},
    "NL": {"zone": "Europe/Amsterdam", "offset": "UTC+1"},
    "NO": {"zone": "Europe/Oslo", "offset": "UTC+1"},
    "NP": {"zone": "Asia/Kathmandu", "offset": "UTC+5:45"},
    "NR": {"zone": "Pacific/Nauru", "offset": "UTC+12"},
    "NU": {"zone": "Pacific/Niue", "offset": "UTC−11"},
    "NZ": {"zone": "Pacific/Auckland", "offset": "UTC+12"},
    "OM": {"zone": "Asia/Muscat", "offset": "UTC+4"},
    "PA": {"zone": "America/Panama", "offset": "UTC−5"},
    "PE": {"zone": "America/Lima", "offset": "UTC−5"},
    "PF": {"zone": "Pacific/Tahiti", "offset": "UTC−10"},
    "PG": {"zone": "Pacific/Port_Moresby", "offset": "UTC+10"},
    "PH": {"zone": "Asia/Manila", "offset": "UTC+8"},
    "PK": {"zone": "Asia/Karachi", "offset": "UTC+5"},
    "PL": {"zone": "Europe/Warsaw", "offset": "UTC+1"},
    "PM": {"zone": "America/Miquelon", "offset": "UTC−3"},
    "PN": {"zone": "Pacific/Pitcairn", "offset": "UTC−8"},
    "PR": {"zone": "America/Puerto_Rico", "offset": "UTC−4"},
    "PS": {"zone": "Asia/Gaza", "offset": "UTC+2"},
    "PT": {"zone": "Europe/Lisbon", "offset": "UTC"},
    "PW": {"zone": "Pacific/Palau", "offset": "UTC+9"},
    "PY": {"zone": "America/Asuncion", "offset": "UTC−4"},
    "QA": {"zone": "Asia/Qatar", "offset": "UTC+3"},
    "RE": {"zone": "Indian/Reunion", "offset": "UTC+4"},
    "RO": {"zone": "Europe/Bucharest", "offset": "UTC+2"},
    "RS": {"zone": "Europe/Belgrade", "offset": "UTC+1"},
    "RU": {"zone": "Europe/Moscow", "offset": "UTC+3"},
    "RW": {"zone": "Africa/Kigali", "offset": "UTC+2"},
    "SA": {"zone": "Asia/Riyadh", "offset": "UTC+3"},
    "SB": {"zone": "Pacific/Guadalcanal", "offset": "UTC+11"},
    "SC": {"zone": "Indian/Mahe", "offset": "UTC+4"},
    "SD": {"zone": "Africa/Khartoum", "offset": "UTC+2"},
    "SE": {"zone": "Europe/Stockholm", "offset": "UTC+1"},
    "SG": {"zone": "Asia/Singapore", "offset": "UTC+8"},
    "SH": {"zone": "Atlantic/St_Helena", "offset": "UTC"},
    "SI": {"zone": "Europe/Ljubljana", "offset": "UTC+1"},
    "SJ": {"zone": "Arctic/Longyearbyen", "offset": "UTC+1"},
    "SK": {"zone": "Europe/Bratislava", "offset": "UTC+1"},
    "SL": {"zone": "Africa/Freetown", "offset": "UTC"},
    "SM": {"zone": "Europe/San_Marino", "offset": "UTC+1"},
    "SN": {"zone": "Africa/Dakar", "offset": "UTC"},
    "SO": {"zone": "Africa/Mogadishu", "offset": "UTC+3"},
    "SR": {"zone": "America/Paramaribo", "offset": "UTC−3"},
    "SS": {"zone": "Africa/Juba", "offset": "UTC+2"},
    "ST": {"zone": "Africa/Sao_Tome", "offset": "UTC"},
    "SV": {"zone": "America/El_Salvador", "offset": "UTC−6"},
    "SX": {"zone": "America/Lower_Princes", "offset": "UTC−4"},
    "SY": {"zone": "Asia/Damascus", "offset": "UTC+2"},
    "SZ": {"zone": "Africa/Mbabane", "offset": "UTC+2"},
    "TC": {"zone": "America/Grand_Turk", "offset": "UTC−5"},
    "TD": {"zone": "Africa/Ndjamena", "offset": "UTC+1"},
    "TF": {"zone": "Indian/Kerguelen", "offset": "UTC+5"},
    "TG": {"zone": "Africa/Lome", "offset": "UTC"},
    "TH": {"zone": "Asia/Bangkok", "offset": "UTC+7"},
    "TJ": {"zone": "Asia/Dushanbe", "offset": "UTC+5"},
    "TK": {"zone": "Pacific/Fakaofo", "offset": "UTC+13"},
    "TL": {"zone": "Asia/Dili", "offset": "UTC+9"},
    "TM": {"zone": "Asia/Ashgabat", "offset": "UTC+5"},
    "TN": {"zone": "Africa/Tunis", "offset": "UTC+1"},
    "TO": {"zone": "Pacific/Tongatapu", "offset": "UTC+13"},
    "TR": {"zone": "Europe/Istanbul", "offset": "UTC+3"},
    "TT": {"zone": "America/Port_of_Spain", "offset": "UTC−4"},
    "TV": {"zone": "Pacific/Funafuti", "offset": "UTC+12"},
    "TW": {"zone": "Asia/Taipei", "offset": "UTC+8"},
    "TZ": {"zone": "Africa/Dar_es_Salaam", "offset": "UTC+3"},
    "UA": {"zone": "Europe/Kyiv", "offset": "UTC+2"},
    "UG": {"zone": "Africa/Kampala", "offset": "UTC+3"},
    "UM": {"zone": "Pacific/Wake", "offset": "UTC+12"},
    "US": {"zone": "America/New_York", "offset": "UTC−5"},
    "UY": {"zone": "America/Montevideo", "offset": "UTC−3"},
    "UZ": {"zone": "Asia/Tashkent", "offset": "UTC+5"},
    "VA": {"zone": "Europe/Vatican", "offset": "UTC+1"},
    "VC": {"zone": "America/St_Vincent", "offset": "UTC−4"},
    "VE": {"zone": "America/Caracas", "offset": "UTC−4"},
    "VG": {"zone": "America/Tortola", "offset": "UTC−4"},
    "VI": {"zone": "America/St_Thomas", "offset": "UTC−4"},
    "VN": {"zone": "Asia/Ho_Chi_Minh", "offset": "UTC+7"},
    "VU": {"zone": "Pacific/Efate", "offset": "UTC+11"},
    "WF": {"zone": "Pacific/Wallis", "offset": "UTC+12"},
    "WS": {"zone": "Pacific/Apia", "offset": "UTC+13"},
    "XK": {"zone": "Europe/Belgrade", "offset": "UTC+1"},
    "YE": {"zone": "Asia/Aden", "offset": "UTC+3"},
    "YT": {"zone": "Indian/Mayotte", "offset": "UTC+3"},
    "ZA": {"zone": "Africa/Johannesburg", "offset": "UTC+2"},
    "ZM": {"zone": "Africa/Lusaka", "offset": "UTC+2"},
    "ZW": {"zone": "Africa/Harare", "offset": "UTC+2"}
}
#uses the main or most populous zone per country, consistent with datasets from IANA and GeoNames

tzoffset_to_regions = {
    "UTC−11": ["AS", "NU"],
    "UTC−10": ["CK", "PF"],
    "UTC−8": ["PN"],
    "UTC−6": ["BZ", "CR", "GT", "HN", "MX", "NI", "SV"],
    "UTC−5": ["BS", "CA", "CO", "CU", "EC", "HT", "JM", "KY", "PA", "PE", "TC", "US"],
    "UTC−4": ["AG", "AI", "AW", "BB", "BL", "BM", "BO", "BQ", "CL", "CW", "DM", "DO", "GD", "GP", "GY", "KN", "LC", "MF", "MQ", "MS", "PR", "PY", "SX", "TT", "VC", "VE", "VG", "VI"],
    "UTC−3": ["AR", "BR", "FK", "GF", "GL", "PM", "SR", "UY"],
    "UTC−2": ["GS"],
    "UTC−1": ["CV"],
    "UTC": ["BF", "CI", "FO", "GB", "GG", "GH", "GM", "GN", "GW", "IE", "IM", "IS", "JE", "LR", "MA", "ML", "MR", "PT", "SH", "SL", "SN", "ST", "TG"],
    "UTC+1": ["AD", "AL", "AO", "AT", "BA", "BE", "BJ", "BV", "CD", "CF", "CG", "CH", "CM", "CZ", "DE", "DK", "DZ", "EH", "ES", "FR", "GA", "GI", "GQ", "HR", "HU", "IT", "LI", "LU", "MC", "ME", "MK", "MT", "NA", "NE", "NG", "NL", "NO", "PL", "RS", "SE", "SI", "SJ", "SK", "SM", "TD", "TN", "VA", "XK"],
    "UTC+2": ["AX", "BG", "BI", "BW", "CY", "EE", "EG", "FI", "GR", "IL", "JO", "LB", "LS", "LT", "LV", "LY", "MD", "MW", "MZ", "PS", "RO", "RW", "SD", "SY", "SZ", "UA", "ZA", "ZM", "ZW"],
    "UTC+3": ["BH", "BY", "DJ", "ER", "ET", "IQ", "KE", "KM", "KW", "MG", "QA", "RU", "SA", "SO", "SS", "TZ", "TR", "UG", "YE", "YT"],
    "UTC+3:30": ["IR"],
    "UTC+4": ["AE", "AM", "AZ", "GE", "MU", "OM", "RE", "SC", "QA"],
    "UTC+4:30": ["AF"],
    "UTC+5": ["HM", "KZ", "MV", "PK", "TF", "TJ", "TM", "UZ"],
    "UTC+5:30": ["IN", "LK"],
    "UTC+5:45": ["NP"],
    "UTC+6": ["BD", "BT", "IO", "KG"],
    "UTC+6:30": ["CC", "MM"],
    "UTC+7": ["CX", "ID", "KH", "LA", "TH", "VN"],
    "UTC+8": ["AQ", "BN", "CN", "HK", "MO", "MN", "MY", "PH", "SG", "TW"],
    "UTC+9": ["JP", "KP", "KR", "PW", "TL"],
    "UTC+10": ["AU", "GU", "MP", "PG"],
    "UTC+11": ["FM", "NC", "NF", "SB", "VU"],
    "UTC+12": ["FJ", "KI", "MH", "NR", "NZ", "TV", "UM", "WF"],
    "UTC+13": ["TK", "TO", "WS"],
    "UTC+5:30": ["IN", "LK"],
    "UTC+5:45": ["NP"],
}